/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.marvin.nihao;

public final class R {
    public static final class array {
        public static final int languages=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int list=0x7f060000;
        public static final int sayhello=0x7f060001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int af=0x7f050002;
        public static final int app_name=0x7f050001;
        public static final int bs=0x7f050003;
        public static final int cy=0x7f050026;
        public static final int cz=0x7f050007;
        public static final int de=0x7f05000e;
        public static final int el=0x7f05000f;
        public static final int enuk=0x7f05000a;
        public static final int enus=0x7f050009;
        public static final int eo=0x7f05000b;
        public static final int es=0x7f05001f;
        public static final int esla=0x7f050020;
        public static final int fi=0x7f05000c;
        public static final int fr=0x7f05000d;
        public static final int hi=0x7f050010;
        public static final int hr=0x7f050006;
        public static final int hu=0x7f050011;
        public static final int id=0x7f050013;
        public static final int instructions=0x7f050000;
        public static final int is=0x7f050012;
        public static final int it=0x7f050014;
        public static final int ku=0x7f050015;
        public static final int la=0x7f050016;
        public static final int mk=0x7f050017;
        public static final int nl=0x7f050008;
        public static final int no=0x7f050018;
        public static final int pl=0x7f050019;
        public static final int pt=0x7f05001a;
        public static final int ro=0x7f05001b;
        public static final int ru=0x7f05001c;
        public static final int sk=0x7f05001e;
        public static final int sr=0x7f05001d;
        public static final int sv=0x7f050022;
        public static final int sw=0x7f050021;
        public static final int ta=0x7f050023;
        public static final int tr=0x7f050024;
        public static final int vi=0x7f050025;
        public static final int zh=0x7f050005;
        public static final int zhyue=0x7f050004;
    }
}
