// Copyright 2009 Google Inc. All Rights Reserved.

/**
 * AIDL for the OCR Service
 * IOcrCallback.java is autogenerated from this
 * 
 * @author alanv@google.com (Alan Viverette)
 */
 
package com.android.ocr.client;

import com.android.ocr.client.Result;

// Declare the interface.
oneway interface IOcrCallback {
  void onResult(in Result results);
  void onCompleted(in Result[] results);
}