// Copyright 2008 Google Inc. All Rights Reserved.

/**
 * AIDL for the TTS Service
 * ITTSCallback.java is autogenerated from this
 * 
 * @author clchen@google.com (Charles L. Chen)
 */
 
package com.google.tts;

// Declare the interface.
oneway interface ITTSCallback {
  void markReached(String mark);
}