/*
 * Copyright 2012 Google Inc.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

/*
 * NOTE: A similar file is generated by the native brltty build system.
 * This file was hand-written for the drivers that are supported on
 * Android.
 */

extern const BrailleDriver brl_driver_vo;
extern const BrailleDriver brl_driver_eu;
extern const BrailleDriver brl_driver_fs;
extern const BrailleDriver brl_driver_hw;
extern const BrailleDriver brl_driver_bm;
extern const BrailleDriver brl_driver_pm;
extern const BrailleDriver brl_driver_hm;
extern const BrailleDriver brl_driver_al;
extern const BrailleDriver brl_driver_sk;
extern const BrailleDriver brl_driver_ht;
static const DriverEntry driverTable[] = {
  {&brl_driver_vo, &brl_driver_vo.definition},
  {&brl_driver_eu, &brl_driver_eu.definition},
  {&brl_driver_fs, &brl_driver_fs.definition},
  {&brl_driver_hw, &brl_driver_hw.definition},
  {&brl_driver_bm, &brl_driver_bm.definition},
  {&brl_driver_pm, &brl_driver_pm.definition},
  {&brl_driver_hm, &brl_driver_hm.definition},
  {&brl_driver_al, &brl_driver_al.definition},
  {&brl_driver_sk, &brl_driver_sk.definition},
  {&brl_driver_ht, &brl_driver_ht.definition},
  {NULL, NULL}
};
