# Copyright 2010 Google Inc. All Rights Reserved.
# Author: dmazzoni@google.com (Dominic Mazzoni)
# -*- mode: python; -*-

java_library(
    name = "Dictionary",
    srcs = [
        "src/com/google/android/marvin/aime/dictionary/AbstractBinaryDictionary.java",
        "src/com/google/android/marvin/aime/dictionary/AbstractBinaryStringDictionary.java",
        "src/com/google/android/marvin/aime/dictionary/Dictionary.java",
    ])
